blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from main import views

urlpatterns = [
    url(r'^$', views.Index.as_view()),
    url(r'^home/', include('main.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^test/', include('effect_test.urls')),
]


if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.conf.urls import url, include
from . import views as MainViews
from entry import views as EntryView


app_name = 'main'
urlpatterns = [
    url(r'^climbing/$', EntryView.ClimbingView.as_view(), name='climbing'),
    url(r'^contact/$', MainViews.ContactView.as_view(), name='contact'),
    url(r'^countries/$', MainViews.CountriesView.as_view(), name='countries'),
    url(r'^aboutus/$', MainViews.AboutUsView.as_view(), name='aboutus'),
    url(r'^articles/', include('entry.urls', namespace="entry")),
    url(r'^$', MainViews.Index.as_view(), name='home'),
]

main/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from cloudinary.models import CloudinaryField

# Create your models here.
class AboutUs(models.Model):
    title = models.CharField(max_length=400)
    # leon_image = models.ImageField(upload_to='aboutus/authors/leon', null=True)
    leon_image = CloudinaryField('leon_image', null=True)
    magda_image = CloudinaryField('magda_image', null=True)

    # magda_image = models.ImageField(upload_to='aboutus/authors/magda', null=True)
    body = RichTextUploadingField()

    class Meta:
        verbose_name_plural = "About Us"


class AboutUsImage(models.Model):
    property = models.ForeignKey(AboutUs, related_name='abus_images')
    # image = models.ImageField(upload_to='aboutus/authors', null=True)
    image = CloudinaryField('image', null=True)

main/views.py
from django.views import generic
from django.utils import timezone
from main.models import AboutUs
from entry import models

class Index(generic.ListView):
    queryset = models.Entry.objects.published()
    template_name = "main/main_index.html"

class AboutUsView(generic.TemplateView):
    template_name = "main/aboutus.html"
    model = AboutUs

    def get_context_data(self, **kwargs):
        context = super(AboutUsView, self).get_context_data(**kwargs)
        context['object_list'] = AboutUs.objects
        return context

class ContactView(generic.TemplateView):
    template_name = "main/contact.html"


class CountriesView(generic.ListView):
    template_name = "main/countries.html"
    queryset = models.Country.objects.all()

main/templates/main/aboutus.html
{% extends 'main/base.html' %}
{% block content %}
{% load staticfiles %}
{% load cloudinary %}
    {% include 'main/main_menu.html'%}
    {% for object in object_list.all %}
    <link rel="stylesheet" type="text/css" href="{% static '/entry/css/entry_list.css' %}">
        <div class="container">
        <div class="row">
			<div class = "col-sm-12">
                <div class="post-item">
                    <div class="title">
                        {{ object.title|safe }}
                    </div>
                    <div class = "row">
                        <div class ="col-sm-6">
                            <span class="img-thumbnai1">
{#                                <img class = "post-image" src="{{ object.leon_image.url }}"/>#}
                                   {% cloudinary object.leon_image class="post-image" format="jpg" quality="80"%}

                            </span>
                        </div>
                        <div class ="col-sm-6">
                            <span class="img-thumbnai1">
{#                                <img class = "post-image" src="{{ object.magda_image.url }}"/>#}
                                {% cloudinary object.magda_image class="post-image" format="jpg" quality="80"%}

                            </span>
                        </div>
                    </div>
                    <div id="post-body" class="text">
                    {{object.body|safe}}
                    </div>
                </div>
			</div>
        </div>
    </div>
    {% endfor %}
{% endblock %}

main/templates/main/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load django_markdown %}
<html lang="en">
<head>
	<title>Polish-German climbing team</title>
	<meta charset="utf-8">
	<meta name="author" content="ntmagda">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <link rel="stylesheet" type="text/css" href="{% static '/main/css/style2.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src = "{% static '/main/js/slideshow.js' %}"></script>
</head>
<body>
{% block content %}
{% endblock %}
<div id="footer">
    Created by Magda Nowak-Trzos
</div>
</body>
</html>

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% block content %}
    {% include 'main/main_menu.html'%}
    <div id="main">
        <div id="content">
            <h1>Contact</h1>
        </div>
            {% include 'main/../../../entry/templates/entry/sidebar.html' %}
    </div>

{% endblock %}

main/templates/main/countries.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% load cloudinary %}
{% block content %}
{% include 'main/main_menu.html'%}
<link rel="stylesheet" type="text/css" href="{% static '/main/css/countires.css' %}">
    <div class="container">
	<div class="row">
    <div class="title">Counries we've visited</div>
        <div class="gallery">
        {% for object in object_list %}
                <div class="image_wrap">
                    <a href="{% url "main:entry:articles-country" slug_country=object.slug %}">
                        <div>
{#                        <img class = "image" src="{{ object.image.url }}"/>#}
                        {% cloudinary object.image class="image" format="jpg" quality="80" %}

                        <p class="img_description text"><span>{{ object.name }}</span></p>
                        </div>
                    </a>
                </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

slug=plant.slug inspection_id=inspection.id

main/templates/main/grid.html
{% extends 'main/base.html' %}
{% load staticfiles %}
{% load cloudinary %}
{% block content %}
{% include 'main/main_menu.html'%}
<link rel="stylesheet" type="text/css" href="{% static '/main/css/grid.css' %}">
    <div class="container">
	<div class="row">
    <div class="title">Counries we've visited</div>
        <div class="gallery">
        {% for object in object_list %}
                <div class="image_wrap">
                    <a href="{% url "main:entry:articles-country" slug_country=object.slug %}">
                        <div>
{#                        <img class = "image" src="{{ object.image.url }}"/>#}
                        {% cloudinary object.image class="image" format="jpg" quality="80" %}

                        <p class="img_description text"><span>{{ object.name }}</span></p>
                        </div>
                    </a>
                </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

slug=plant.slug inspection_id=inspection.id

main/templates/main/main_index.html
{% extends 'main/base.html' %}
{% load django_markdown %}
{% load staticfiles %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static '/main/css/main_sections.css' %}">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<link rel="stylesheet" type="text/css" href="{% static '/entry/css/entry_list.css' %}">
<link href="https://fonts.googleapis.com/css?family=Amatic+SC" rel="stylesheet">
<script>
$(document).ready(function(){
  $(".know_more").on('click', function(event) {
    if (this.hash !== "") {
      event.preventDefault();
      var hash = this.hash;
      $('html, body').animate({
        scrollTop: $(hash).offset().top
      }, 800, function(){
        window.location.hash = hash;
      });
    }
  });
});
</script>

{% include 'main/main_menu.html'%}
       <div class="container-fluid bg-1 text-center" >
            <div class="row" id="section_top_content" style="width: 100vw; height: 100vh">
                <div class="col-sm-12"><span id="P-G" style="background-color: black"> Polish - German <br>climbing team<br><br> </span>
                    <span style="font-size: 4vh"> WE #STAYATHOME </span>
                </div>
            </div>
                <div id="know_more">
                    <a href="#section_bottom" class ="know_more" >Find out more</a>
                </div>
       </div>
    <div class ="container bg-2 text-center" id ="section_bottom">
        {% include "main/section_bottom.html" with object=object_list|first  %}
    </div>
{% endblock %}

main/templates/main/main_menu.html
{%  load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static '/main/css/main_menu2.css' %}">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <ul class="nav navbar-nav pull-left">
{#          <li class="active social">#}
{#                <a href="https://www.facebook.com/magda.nowaktrzos" style=" height:5vh;width:5vh; background-color: transparent;">#}
{#                  <img id="Image1" src="{% static 'images/social_media/facebook_icon.png' %} " style="height:5vh;width:5vh;" />#}
{#                </a>#}
{#          </li>#}
          <li class ="active social">
                <a href="https://www.instagram.com/ntmagda/" style=" height:5vh;width:5vh; background-color: transparent;" >
                  <img id="insta_icon" src="{% static 'images/social_media/instagram_icon.png' %} " style="height:5vh;width:5vh;" />
                </a>
          </li>
        </ul>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main_menu">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse " id="main_menu">
      <ul class="nav navbar-nav">
            <li><a href="{% url 'main:home' 		    %}">Home</a></li>
            <li><a href="{% url 'main:aboutus' 		    %}">About us</a></li>
            <li><a href="{% url 'main:entry:articles' 	%}">Articles</a></li>
            <li><a href="{% url 'main:countries'   	    %}">Countries</a></li>
{#            <li><a href="{% url 'main:climbing' 		%}">Climbing</a></li>#}
{#            <li><a href="{% url 'main:contact' 	    	%}">How to live?</a></li>#}
      </ul>
    </div>
  </div>
</nav>

main/templates/main/multi_slider.html
{% load cloudinary %}
{% load staticfiles %}
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link rel="stylesheet"  href="{% static 'entry/css/multi_slider.css' %}"/>
<style>
    ul{
        list-style: none outside none;
        padding-left: 0;
        margin: 0;
    }
    .demo .item{
{#        margin-bottom: 60px;#}
    }
    .content-slider li{
        text-align: center;
        color: #FFF;
    }
    .content-slider h3 {
        margin: 0;
{#        padding: 20px 0;#}
    }
    .demo{
        width: 100%;
    }
</style>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="{% static 'entry/js/multi_slider.js' %}"></script>
<script>
     $(document).ready(function() {
        $("#content-slider").lightSlider({
            loop:true,
            keyPress:true
        });
        $('#image-gallery').lightSlider({
            gallery:true,
            item:1,
            thumbItem:9,
            slideMargin: 0,
            speed:500,
            auto:true,
            loop:true,
            onSliderLoad: function() {
                $('#image-gallery').removeClass('cS-hidden');
            }
        });
    });
</script>
<div class="demo">
    <div class="item">
        <ul id="content-slider" class="content-slider">
    {% for object in object_list %}
        <li>
            <h3>
            <div class = "image">
                <a href="{% url 'main:entry:entry-detail' object.slug %}">
{#                    <img class = "post-image" src="{{ object.title_image.url }}"/>#}
                    {% cloudinary object.title_image class="post-image" format="jpg" quality="80" %}

                    <p class="img_description text">{{ object.title }}</p>
                </a>
            </div>
            </h3>
        </li>
    {% endfor %}
        </ul>
    </div>
</div>

main/templates/main/section_bottom.html
{% load embed_video_tags %}
{% load cloudinary %}
<div class="row" >
    <div class="col-sm-9">
        <div class="post-item">
            {% with object_list|first as object %}
            <div class="title">
                <a href="{% url 'main:entry:entry-detail' object.slug %}">{{ object.title|safe }}</a>
            </div>
            <div class ="info">
                <span class="date">created on {{ object.created|date:'d.m.Y'}}</span>
                <span class = "author">
                    by <a href = "{% url 'main:aboutus' %}">{{ object.author|safe }}</a>
                </span>
            </div>
            {% if object.entry_video %}
                {% video object.entry_video as my_video %}
                    <div class="intrinsic-container intrinsic-container-16x9">
                        <iframe
                        src="{{ my_video.url }}?portrait=0&amp;color=ff0179&amp;" frameborder="0" allowFullScreen>
                        </iframe>
                    </div>
                {% endvideo %}
                {% else %}
                <div class = "image">
                <a href="{% url 'main:entry:entry-detail' object.slug %}" class="img-thumbnai1">
                      {% cloudinary object.title_image class="post-image" format="jpg" quality="80"%}

                </a>
            </div>
            {% endif %}
            <div id="short-body" class ="text">
                {{object.short_body}}
            </div>
            <div id="slideshow">
                {% include 'main/slideshow.html' %}
            </div>
            <div id="post-body" class="text">
            {{object.body|safe}}
            </div>
            {% endwith %}
        </div>
        <div class="title">
            Recent articles
        </div>
        <div id="recent_articles" class="row_images">
            {% include "main/multi_slider.html" with object_list=object_list|slice:"1:" %}
        </div>
    </div>
    <div class="col-sm-3" >{% include 'entry/sidebar.html' %}</div>
</div>

main/templates/main/slideshow.html
<!DOCTYPE html>

{% load django_markdown %}
{% load staticfiles %}
{% load cloudinary %}
    <link rel="stylesheet" type="text/css" href="{% static '/main/css/slideshow.css' %}">
        <div id="slideshow1" >
            {% for image in object.images.all %}
                 <div class="mySlides fade1" >
{#                    <img src="{{ image.image.url }}" style="width:100%; opacity: 1"/>#}
                     {% cloudinary image.image.url format="jpg" quality="80" style="width:100%; opacity: 1"%}

                </div>
            {% endfor %}
            <div><a class="prev" onclick="plusSlides(-1)">&#10094;</a></div>
            <div><a class="next" onclick="plusSlides(1)">&#10095;</a></div>
    </div>